#!/bin/bash

function usage() {
    echo ""
    echo "Usage: $0 COMMAND"
    echo ""
    echo "Commands:"
    echo "  init     Create some init directories and links and up your app"
    echo "  up       Up your app"
    echo "  bash     Enters php container"
    echo "  tinker   Runs tinker inside container"
    echo "  docs     Generates phpdocs for models"
    echo ""
    exit 1
}

function up() {

    echo "=============================="
    echo "Stop and remove current images"
    echo "=============================="
    docker-compose rm -s -f

    echo "========="
    echo "Up images"
    echo "========="
    docker-compose build
    docker-compose up -d

    echo "==============="
    echo "Update composer"
    echo "==============="
    docker-compose run --rm fpm bash -c "composer update && chown -R www-data:1000 /app/vendor /app/composer.lock"

    echo "================="
    echo "Update migrations"
    echo "================="
    docker-compose run --rm fpm bash -c "php artisan key:generate && php artisan migrate && chown -R www-data:1000 /app/storage"
}

function init() {
    echo "================================"
    echo "Copy .env"
    echo "================================"
    if [[ ! -e ../.env ]]; then
        cp ../.env.example ../.env
        chown 1000:1000 ../.env
    fi

    up

    echo "======================================="
    echo "Create system app directories and links"
    echo "======================================="
    docker-compose run --rm fpm bash -c "mkdir -p /app/docker/data/{db,app,nginx,php,sendmail} && touch /app/docker/data/app/{application.log,cron.log,notify.log} && chown -R www-data:1000 /app/docker/data/{app,nginx,php,sendmail}"
    docker-compose run --rm fpm bash -c "php artisan storage:link -q && chown -R www-data:1000 /app/storage"
    docker-compose run --rm fpm bash -c "php artisan jwt:secret"
}

function bash() {
    echo "=============================="
    echo "Enter into php container using bash"
    echo "=============================="
    docker-compose run --rm -u 1000 fpm bash
}

function tinker() {
    echo "=============================="
    echo "Enter into php container using bash"
    echo "=============================="
    docker-compose run --rm fpm bash -c "php artisan tinker"
}

function docs() {
    echo "=============================="
    echo "Generate docs for models"
    echo "=============================="
    docker-compose run --rm fpm bash -c "php artisan migrate:fresh"
    docker-compose run --rm -u 1000 fpm bash -c "php /app/artisan ide-helper:models -W"
}


function main() {
    if [[ "$#" -ne 1 ]]; then
        usage
        exit 1
    fi

    case "$1" in
        "up")
            up
            ;;
        "init")
            init
            ;;
        "docs")
            docs
            ;;
        "bash")
            bash
            ;;
        "tinker")
            tinker
            ;;
        *)
            usage
            ;;
    esac
}

main "$@"
