version: '3.5'

x-app-mount:
  &app-mount
  type: bind
  source: ../
  target: /app

services:
  nginx:
    network_mode: host
    hostname: nginx
    image: nginx:alpine
    container_name: rehearsal-nginx
    restart: unless-stopped
    volumes:
      - *app-mount
      - ./nginx/dev/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/:/var/log/nginx

  fpm:
    working_dir: /app
    hostname: rehearsals-php-fpm
    container_name: rehearsal-php
    build:
      context: ./php/
    volumes:
      - *app-mount
      - ./data/php/:/var/log/php7-fpm
      - ./php/app-config.ini:/usr/local/etc/php/conf.d/app-config.ini
      - ./php/dev/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./php/cron/crontab.main:/crontab/crontab.main
    environment:
      - XDEBUG_CONFIG="idekey=PHPSTORM remote_enable=On remote_port=9001 profiler_enable_trigger=On profiler_output_dir=/app/docker/data/php/profile"
    ports:
      - 127.0.0.1:9000:9000
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: rehearsal-db
    hostname: db
    volumes:
      - *app-mount
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - database.env
    ports:
      - 5432:5432