version: '3.5'

services:
  php:
    working_dir: /app
    hostname: rehearsals-php
    container_name: rehearsal-php
    build:
      context: ./php/
    volumes:
      - ../:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rehearsals
      - POSTGRES_USER=rehearsals
      - POSTGRES_PASSWORD=rehearsals
    ports:
      - 5432:5432