version: '3.5'

services:
  php:
    hostname: rehearsals-php
    image: rehearsals-backend
    build:
      context: ../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=rehearsals
      - POSTGRES_USER=rehearsals
      - POSTGRES_PASSWORD=rehearsals
    ports:
      - 5432:5432