version: '3.5'

services:
  php:
    image: backend
    build:
      context: ../
      dockerfile: docker/ci/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=rehearsals
      - POSTGRES_USER=rehearsals
      - POSTGRES_PASSWORD=rehearsals
    ports:
      - "5432:5432"